apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  labels:
    app.kubernetes.io/name: pprof-operator
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "your-access-key"
  AWS_SECRET_ACCESS_KEY: "your-secret-key"