---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - observability.pprof-operator.dev
  resources:
  - profilers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - observability.pprof-operator.dev
  resources:
  - profilers/finalizers
  verbs:
  - update
- apiGroups:
  - observability.pprof-operator.dev
  resources:
  - profilers/status
  verbs:
  - get
  - patch
  - update
